site_name: 天文技术宅
site_description: 星空属于每一个人
site_author: Charon,Xia0-0

theme:
  name: material
  favicon: assets/images/favicon1.ico
  logo: assets/images/logo.jpg
  palette:
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 长夜漫漫
    - scheme: light
      primary: white
      accent: teal
      toggle:
        icon: material/theme-light-dark
        name: 旭日东升


extra_css:
  - assets/css/index.css

nav:
  - 首页: index.md

  - 科普资源:
      - 科普和科幻书籍: popsci/books.md
      - 影视和纪录片: popsci/videos.md
      - 公开课和课程资源: popsci/courses.md
      - 公众号和自媒体: popsci/accounts.md

  - 专业介绍: 
      - 专业基本情况: intro/basic.md
      - 专业方向: intro/areas.md
      - 开设院校情况: intro/unis.md
      - 入门书籍: intro/books.md
      - 职业生涯路线: intro/paths.md
      - 专业资源: intro/resources.md
    
  - 专业课程:
      - 数学物理课程: course/mathphys.md
      - 计算机课程: course/computer.md
      - 天文课程: course/astronomy.md
  
  - 科研入门:
      - 系统环境和Python基础: research/python.md
      - 望远镜观测基础: research/observation.md
      - 常用数据库: research/databases.md
      - Python天文数据处理: research/dataproc.md
      - 测光: research/photometry.md
      - 光谱分析: research/spectroscopy.md
      - 其它波段数据处理: research/otherdata.md
      - 数据处理软件: research/software.md
      - 其它工具: research/othertools.md
