site_name: Hello-Astronomy
site_description: 探索有趣的旅程
site_author: Xia0-0&xxxx
theme:
  name: material




nav:
  - 首页: index.md
  - 基础入门:
      - 太阳系: basic.md
      - 宇宙结构: universe_structure.md
      - 星系: galaxies.md
      - 星系团: galaxy_clusters.md
  - 实用技术:
      - 天文望远镜: telescope.md
      - 数学: mathematics.md
  - 其他:
      - 其他技术: other_technology.md
      - 资源链接: resources.md
      
 